//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class OnnxModel : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OnnxModel(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OnnxModel obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OnnxModel obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OnnxModel() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TornadoPredictorOnnxPINVOKE.delete_OnnxModel(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool usingGPU {
    set {
      TornadoPredictorOnnxPINVOKE.OnnxModel_usingGPU_set(swigCPtr, value);
    } 
    get {
      bool ret = TornadoPredictorOnnxPINVOKE.OnnxModel_usingGPU_get(swigCPtr);
      return ret;
    } 
  }

  public OnnxModel(string modelPath, string modelName, uint batchSize) : this(TornadoPredictorOnnxPINVOKE.new_OnnxModel(modelPath, modelName, batchSize), true) {
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
  }

  public void initializeTensors(int inputSize, int predicitionSize) {
    TornadoPredictorOnnxPINVOKE.OnnxModel_initializeTensors(swigCPtr, inputSize, predicitionSize);
  }

  public void predict() {
    TornadoPredictorOnnxPINVOKE.OnnxModel_predict(swigCPtr);
  }

}
