//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public partial class TornadoPatchPredictor64_256 : OnnxModel {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal TornadoPatchPredictor64_256(global::System.IntPtr cPtr, bool cMemoryOwn) : base(TornadoPredictorOnnxPINVOKE.TornadoPatchPredictor64_256_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TornadoPatchPredictor64_256 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TornadoPatchPredictor64_256 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TornadoPredictorOnnxPINVOKE.delete_TornadoPatchPredictor64_256(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public TornadoPatchPredictor64_256(string path) : this(TornadoPredictorOnnxPINVOKE.new_TornadoPatchPredictor64_256(path), true) {
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
  }

  public ByteVector analyze(ByteVector before, ByteVector after, int width, int height) {
    ByteVector ret = new ByteVector(TornadoPredictorOnnxPINVOKE.TornadoPatchPredictor64_256_analyze(swigCPtr, ByteVector.getCPtr(before), ByteVector.getCPtr(after), width, height), true);
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
