//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class TornadoPredictorOnnx {
  public unsafe static SWIGTYPE_p_std__spanT_unsigned_char_t createSpan(SWIGTYPE_p_unsigned_char spanArray, int size) {
    SWIGTYPE_p_std__spanT_unsigned_char_t ret = new SWIGTYPE_p_std__spanT_unsigned_char_t(TornadoPredictorOnnxPINVOKE.createSpan__SWIG_0(SWIGTYPE_p_unsigned_char.getCPtr(spanArray), size), true);
    return ret;
  }

  public unsafe static SWIGTYPE_p_std__spanT_float_t createSpan(SWIGTYPE_p_float spanArray, int size) {
    SWIGTYPE_p_std__spanT_float_t ret = new SWIGTYPE_p_std__spanT_float_t(TornadoPredictorOnnxPINVOKE.createSpan__SWIG_1(SWIGTYPE_p_float.getCPtr(spanArray), size), true);
    return ret;
  }

  public static int getSpanSize(SWIGTYPE_p_std__spanT_unsigned_char_t span) {
    int ret = TornadoPredictorOnnxPINVOKE.getSpanSize__SWIG_0(SWIGTYPE_p_std__spanT_unsigned_char_t.getCPtr(span));
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int getSpanSize(SWIGTYPE_p_std__spanT_float_t span) {
    int ret = TornadoPredictorOnnxPINVOKE.getSpanSize__SWIG_1(SWIGTYPE_p_std__spanT_float_t.getCPtr(span));
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_unsigned_char getSpanPtr(SWIGTYPE_p_std__spanT_unsigned_char_t span) {
    global::System.IntPtr cPtr = TornadoPredictorOnnxPINVOKE.getSpanPtr__SWIG_0(SWIGTYPE_p_std__spanT_unsigned_char_t.getCPtr(span));
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_float getSpanPtr(SWIGTYPE_p_std__spanT_float_t span) {
    global::System.IntPtr cPtr = TornadoPredictorOnnxPINVOKE.getSpanPtr__SWIG_1(SWIGTYPE_p_std__spanT_float_t.getCPtr(span));
    SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void freeSpan(SWIGTYPE_p_std__spanT_unsigned_char_t span) {
    TornadoPredictorOnnxPINVOKE.freeSpan__SWIG_0(SWIGTYPE_p_std__spanT_unsigned_char_t.getCPtr(span));
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void freeSpan(SWIGTYPE_p_std__spanT_float_t span) {
    TornadoPredictorOnnxPINVOKE.freeSpan__SWIG_1(SWIGTYPE_p_std__spanT_float_t.getCPtr(span));
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe static ByteVector createVector(byte[] sourceArray, int size) {
    fixed ( byte* swig_ptrTo_sourceArray = sourceArray ) {
    {
      ByteVector ret = new ByteVector(TornadoPredictorOnnxPINVOKE.createVector__SWIG_0((global::System.IntPtr)swig_ptrTo_sourceArray, size), true);
      return ret;
    }
    }
  }

  public unsafe static FloatVector createVector(float[] sourceArray, int size) {
    fixed ( float* swig_ptrTo_sourceArray = sourceArray ) {
    {
      FloatVector ret = new FloatVector(TornadoPredictorOnnxPINVOKE.createVector__SWIG_1((global::System.IntPtr)swig_ptrTo_sourceArray, size), true);
      return ret;
    }
    }
  }

  public static ByteVector createByteVector(int size) {
    ByteVector ret = new ByteVector(TornadoPredictorOnnxPINVOKE.createByteVector(size), true);
    return ret;
  }

  public static FloatVector createFloatVector(int size) {
    FloatVector ret = new FloatVector(TornadoPredictorOnnxPINVOKE.createFloatVector(size), true);
    return ret;
  }

  public static SWIGTYPE_p_unsigned_char getVector(ByteVector sourceVector) {
    global::System.IntPtr cPtr = TornadoPredictorOnnxPINVOKE.getVector__SWIG_0(ByteVector.getCPtr(sourceVector));
    SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_float getVector(FloatVector sourceVector) {
    global::System.IntPtr cPtr = TornadoPredictorOnnxPINVOKE.getVector__SWIG_1(FloatVector.getCPtr(sourceVector));
    SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    if (TornadoPredictorOnnxPINVOKE.SWIGPendingException.Pending) throw TornadoPredictorOnnxPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
